"""add paid_online to orders

Revision ID: 024bf1efd964
Revises: 4e4317d85185
Create Date: 2025-02-10 17:38:21.214875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024bf1efd964'
down_revision: Union[str, None] = '4e4317d85185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paid_online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_online')
    # ### end Alembic commands ###
