"""add cost and price to order item

Revision ID: 239d5203491a
Revises: da53bbe37aeb
Create Date: 2025-02-10 02:16:29.020810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239d5203491a'
down_revision: Union[str, None] = 'da53bbe37aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('cost', sa.DECIMAL(precision=7, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('price', sa.DECIMAL(precision=7, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    op.drop_column('order_items', 'cost')
    # ### end Alembic commands ###
