"""empty message

Revision ID: 36c70cf3e68e
Revises: a22863d00400
Create Date: 2024-11-04 15:29:58.922345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c70cf3e68e'
down_revision: Union[str, None] = 'a22863d00400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu_items', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
