"""add is_deleted

Revision ID: 4db6c291a656
Revises: 024bf1efd964
Create Date: 2025-02-11 15:42:29.121599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db6c291a656'
down_revision: Union[str, None] = '024bf1efd964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('menu_items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('order_items', sa.Column('type', sa.Enum('BY_WEIGHT', 'BY_QUANTITY', name='menuitemtypeenum'), nullable=False))
    op.add_column('order_items', sa.Column('weight', sa.Integer(), nullable=False))
    op.add_column('tables', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('tables', 'is_deleted')
    op.drop_column('order_items', 'weight')
    op.drop_column('order_items', 'type')
    op.drop_column('menu_items', 'is_deleted')
    op.drop_column('menu_categories', 'is_deleted')
    # ### end Alembic commands ###
