"""add weight to menu item

Revision ID: 4e4317d85185
Revises: 239d5203491a
Create Date: 2025-02-10 02:42:32.706979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4317d85185'
down_revision: Union[str, None] = '239d5203491a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('weight', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'weight')
    # ### end Alembic commands ###
