"""unique only for undeleted

Revision ID: 8e554c113d41
Revises: 4db6c291a656
Create Date: 2025-02-11 21:22:40.144083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e554c113d41'
down_revision: Union[str, None] = '4db6c291a656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_categories_name_key', 'menu_categories', type_='unique')
    op.create_index('unique_menu_category_name', 'menu_categories', ['name'], unique=True, postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_constraint('tables_name_key', 'tables', type_='unique')
    op.create_index('unique_table_name', 'tables', ['name'], unique=True, postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index('unique_user_username', 'users', ['username'], unique=True, postgresql_where=sa.text('is_deleted = FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_username', table_name='users', postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index('unique_table_name', table_name='tables', postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_unique_constraint('tables_name_key', 'tables', ['name'])
    op.drop_index('unique_menu_category_name', table_name='menu_categories', postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_unique_constraint('menu_categories_name_key', 'menu_categories', ['name'])
    # ### end Alembic commands ###
