"""orders and order items

Revision ID: 9bba17e3fe69
Revises: b52200b4a187
Create Date: 2025-01-06 23:27:23.112591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bba17e3fe69'
down_revision: Union[str, None] = 'b52200b4a187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DINEIN', 'TOGO', name='ordertypeenum'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by_card', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('paid_by_cash', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE TYPE menuitemtypeenum AS ENUM ('BY_WEIGHT', 'BY_QUANTITY')")
    op.add_column('menu_items', sa.Column('type', sa.Enum('BY_WEIGHT', 'BY_QUANTITY', name='menuitemtypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'type')
    op.execute("DROP TYPE menuitem_type")
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('tables')
    # ### end Alembic commands ###
