"""add order paid_by

Revision ID: da53bbe37aeb
Revises: f3c467ee9ad6
Create Date: 2025-02-08 01:13:42.509121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da53bbe37aeb'
down_revision: Union[str, None] = 'f3c467ee9ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paid_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['paid_by'], ['id'])
    op.alter_column('tables', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'paid_by')
    # ### end Alembic commands ###
