"""table is free add

Revision ID: f3c467ee9ad6
Revises: 2785eb5ea209
Create Date: 2025-01-26 19:35:50.383587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f3c467ee9ad6'
down_revision: Union[str, None] = '2785eb5ea209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_free', sa.Boolean(), nullable=True, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_free')
    # ### end Alembic commands ###
